routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categorias', 'CategoriaController');
Route::resource('presentaciones', 'PresentacionController');


Route::resource('compras','CompraController');


Route::resource('presentaciones', 'PresentacionController');



//Route::get('/home/inventariomedicamento', 'ControllerInventario@index')->name('index');
Route::resource('inventario', 'ControllerInventario');
//Route::resource('inventario', 'inventario');


//Rutas de ventas
Route::resource('ventas','VentasController');
Route::get('/buscador','VentasController@buscador')->name('buscador');
Route::post('/buscador','VentasController@buscador')->name('buscador');
Route::get('/movimientos','VentasController@movimiento')->name('movimiento');

//Route del funcional inventario
Route::resource('medicamentos','MedicamentoController');
//Route::post('/medicamentos/{id}/update','MedicamentoController@update');

//Rutas para catalogo de existencias
Route::resource('catalogo','CatalogoExistenciaController');

//Rutas del kardex
Route::resource('kardex','RegistroController');

//sucursales
Route::resource('sucursal','SucursalController');
//::get('/sucursal', 'SucursalController@index');
/*Route::get('/create','SucursalController@vista') ;
Route::post('/create','SucursalController@create') ;
Route::get('/versucursales','SucursalController@read')->name('sucursales');*/

// vendedores
Route::resource('vendedor','VendedorController');
Route::get('/vendedor', 'VendedorController@index');
Route::get('/vendedorver', 'VendedorController@show');

Route::middleware(['auth'])->group(function(){
	//Roles
	Route::post('roles/store', 'RoleController@store')->name('roles.store')
	->middleware('permission:roles.create');

	Route::get('roles', 'RoleController@index')->name('roles.index')
	->middleware('permission:roles.index');

	Route::get('roles/create', 'RoleController@create')->name('roles.create')
	->middleware('permission:roles.create');

	Route::put('roles/{role}', 'RoleController@update')->name('roles.update')
	->middleware('permission:roles.edit');

	Route::get('roles/{role}', 'RoleController@show')->name('roles.show')
	->middleware('permission:roles.show');

	Route::delete('roles/{role}', 'RoleController@destroy')->name('roles.destroy')
	->middleware('permission:roles.destroy');

	Route::get('roles/{role}/edit', 'RoleController@edit')->name('roles.edit')
	->middleware('permission:roles.edit');

	//Usuarios
	Route::get('users', 'UserController@index')->name('users.index')
	->middleware('permission:users.index');

	Route::put('users/{user}', 'UserController@update')->name('users.update')
	->middleware('permission:users.edit');

	Route::get('users/{user}', 'UserController@show')->name('users.show')
	->middleware('permission:users.show');

	Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy')
	->middleware('permission:users.destroy');

	Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit')
	->middleware('permission:users.edit');

});

app/Compra.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Compra extends Model
{
    //
    	 protected $table = 'compras';
         protected $fillable = ['fecha', 'proveedor', 'total',];

         public function detalleCompra()
         {
         	return $this->hasMany('App\DetalleCompra', 'compras_id', 'id');
         }
}

app/Http/Controllers/CompraController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Compra;
use App\DetalleCompra;
use App\Lote;

class CompraController extends Controller
{
    
    public function index()
    {
        //
        $compras = Compra::orderBy('id','DESC')->paginate(10);
        return view('compras.index', compact('compras'));
    }

    public function create()
    {
        //
        return view('compras.create');
    }

    public function store(Request $request)
    {
        //
        $data = request()->all();
        $total = 0;        $detalleP = $data['precio'];
        $detalleC = $data['cantidad'];
        #calcular el precio
        while (true) {
            # code...
            $precio = current($detalleP);
            $cantidad = current($detalleC);
            $total = $total + ($precio * $cantidad);
            $precio = next($detalleP);
            $cantidad = next($detalleC);

            if($precio === false && $cantidad === false ) break;
        
        }
        #Crear la compra
        $compra = Compra::create([
            'fecha'      => $data['fecha'],
            'proveedor' => $data['proveedor'],
            'total' => $total,
            ]);
        $lotesD = $data['descripcion'];
        $lotesF = $data['fechaVencimiento'];
        $detalleP = $data['precio'];
        $detalleC = $data['cantidad'];

        while (true) {
            # code...
            $descripcion = current($lotesD);
            $fecha = current($lotesF);
            $precio = current($detalleP);
            $cantidad = current($detalleC);

            $lote = Lote::create([
            'fechaVencimiento'      => $fecha,
            'descripcion' => $descripcion,
            ]);

            DetalleCompra::create([
            'compras_id' => $compra['id'],
            'lotes_id' => $lote['id'],
            'precio' => $precio,
            'cantidad' => $cantidad,
            ]);
            


            $descripcion = next($lotesD);
            $fecha = next($lotesF);
            $precio = next($detalleP);
            $cantidad = next($detalleC);

            if($descripcion === false && $fecha === false && $precio === false && $cantidad === false ) break;

        
        }
/*        error_log("HOLA AQUI EMPIEZA LA IMPRESION DE LO QUE NO SE************************************************************************ ");
        error_log(" ".$total);
        error_log(" ".$compra);
*/        
        return redirect()->route('compras.index');
    }

    public function edit($id)
    {
        //
        $compra = Compra::find($id);
        return view('compras.edit', compact('compra'));
    }

    public function update(Request $request, $id)
    {
        //
        $data = request()->all();

        $compra = Compra::find($id);
        $compra->update([
            'fecha'      => $data['fecha'],
            'proveedor' => $data['proveedor'],
            'total' => $data['total'],
            ]);
        return redirect()->route('compras.index');
    }

    public function destroy($id)
    {
        //
        $compra = Compra::find($id);
        $compra->delete();
        return back()->with('info', 'La compra: '.$compra->id.', fue eliminada');
    }
    public function show($id){

        $detalles = Compra::find($id)->detalleCompra;
        $lotes = array();
        $arreglo = array();
        foreach($detalles as $de) {
            # code...
            $lote = Lote::find($de['lotes_id']);
            $arr = array (
                'descripcion' => $lote['descripcion'],
                'fechaVencimiento' =>$lote['fechaVencimiento'],
                'precio' => $de['precio'],
                'cantidad' => $de['cantidad'],
            );
            array_push($arreglo, $arr);
        }
        
        return view('compras.show', compact('arreglo'));

        

    }
}

resources/views/compras/create.blade.php
@extends('layouts.layout')

@section('title')
Compra - Nuevo
@endsection

@section('content')
<h2>Nueva Compra</h2>
<form class="form-inline" style="width:100%" action="{{ route('compras.store' )}}" method="POST">
	{{ csrf_field() }}
	<div class="form-group">
		<label for="fecha">Fecha :</label><br>
		<input type="date" class="form-control"  name="fecha">
	</div>
	<div class="form-group">
		<label for="proveedor">Proveedor :</label><br>
		<input type="text" class="form-control"  name="proveedor">
	</div><br><br>
	<table class="table bg-info"  id="tabla">
					<tr class="fila-fija">
						<td><input required name="descripcion[]" type="text" placeholder="Descripcion"/></td>
						<td><input required name="fechaVencimiento[]" 
						type="date"	placeholder="Fecha de vencimiento"/></td>
						<td><input required name="precio[]" 
						type="number"	step="0.01" placeholder="Precio"/></td>
						<td><input required name="cantidad[]" 
						type="number"	step="1" placeholder="Cantidad"/></td>
						<td class="eliminar "><button type="button" class="btn btn-danger">Menos - </button></td>
					</tr>
				</table>

	<button type="submit" class="btn btn-success">Guardar</button>
	<button id="adicional" name="adicional" type="button" class="btn btn-warning"> Más + </button>
	<button type="button" class="btn btn-secondary"><a style="text-decoration:none;color:black" href="{{ route('compras.index')}}">Cancelar</a></button>
</form>

<script>
			
    		$(function(){
				// Clona la fila oculta que tiene los campos base, y la agrega al final de la tabla
				$("#adicional").on('click', function(){
					$("#tabla tbody tr:eq(0)").clone().removeClass('fila-fija').appendTo("#tabla");
				});
			 
				// Evento que selecciona la fila y la elimina 
				$(document).on("click",".eliminar",function(){
					var parent = $(this).parents().get(0);
					$(parent).remove();
				});
			});
		</script>
@endsection

resources/views/compras/edit.blade.php
@extends('layouts.layout')

@section('title')
Compra - Edicion
@endsection

@section('content')
<h2>Edicion de: {{$compra->id}}</h2>
<form class="form-inline" style="width:100%" action="{{ route('compras.update', $compra->id)}}" method="POST">
	{{ csrf_field() }}

	<input name="_method" value="PUT" type="hidden"> 

	<div class="form-group">
		<label for="fecha">Fecha:</label><br>
		<input type="date" class="form-control" style="width:100%" name="fecha" value="{{ $compra->fecha }}">
	</div><br><br>
	<div class="form-group">
		<label for="proveedor">Proveedor:</label><br>
		<input type="text" class="form-control" style="width:100%" name="proveedor" value="{{ $compra->proveedor }}">
	</div><br><br>
	<div class="form-group">
		<label for="total">Total:</label><br>
		<input type="number" class="form-control" style="width:100%" name="total" value="{{ $compra->total }}">
	</div><br><br>

	<button type="submit" class="btn btn-success">Guardar</button>
	<button type="button" class="btn btn-secondary"><a style="text-decoration:none;color:black" href="{{ route('compras.index')}}">Cancelar</a></button>
</form>
@endsection

resources/views/compras/index.blade.php
@extends('layouts.layout')

@section('title')
Compras
@endsection

@section('title-1')
GESTION DE COMPRAS
@endsection

@section('content')
	
	<div class="clo-sm-8">
		<h2>
			Lista de compras
			<a href="{{ route('compras.create')}}" class="btn btn-primary pull-right">Nuevo</a>
		</h2>		

		@include('compras.fragment.info')
	<table class="table table-hover table-striped">
		<thead>
			<tr>
				<th width="20px">ID</th>
				<th>Fecha </th>
				<th>proveedor</th>
				<th>total</th>
				<th colspna="3">Acciones</th>
			</tr>
			<tbody>
				@foreach($compras as $compra)
				<tr>
					<td>{{ $compra->id }}</td>
					<td>{{ $compra->fecha }}</td>
					<td>{{ $compra->proveedor }}</td>
					<td>{{ $compra->total}} </td>
					<td>
						<a href="{{ route('compras.show', $compra->id)}}" class="btn btn-warning pull-right">Detalles</a>
					</td>
				</tr>
				@endforeach
			</tbody>
		</thead>
	</table>
	{!! $compras->render() !!}
	</div>
@endsection

resources/views/compras/show.blade.php
@extends('layouts.layout')
@section('title')
Compra - Detalle
@endsection

@section('content')
<h2>Detalles Compra</h2>
		
	<table class="table table-hover table-striped">
		<thead>
			<tr>
				<th>Descripcion</th>
				<th>Fecha de vencimiento</th>
				<th>Precio</th>
				<th>Total</th>
			</tr>
			<tbody>
				@foreach($arreglo as $de)
				<tr>
					<td>{{ $de['descripcion'] }}</td>
					<td>{{ $de['fechaVencimiento'] }}</td>
					<td>{{ $de['precio'] }}</td>
					<td>{{ $de['cantidad'] }} </td>
				</tr>
				@endforeach
			</tbody>
		</thead>
	</table>
		<button type="button" class="btn btn btn-success"><a style="text-decoration:none;color:black" href="{{ route('compras.index')}}">Regresar</a></button>


@endsection