routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categorias', 'CategoriaController');
Route::resource('presentaciones', 'PresentacionController');


Route::resource('compras','CompraController');


Route::resource('presentaciones', 'PresentacionController');



//Route::get('/home/inventariomedicamento', 'ControllerInventario@index')->name('index');
Route::resource('inventario', 'ControllerInventario');
//Route::resource('inventario', 'inventario');


//Rutas de ventas
Route::resource('ventas','VentasController');
Route::get('/buscador','VentasController@buscador')->name('buscador');
Route::post('/buscador','VentasController@buscador')->name('buscador');
Route::get('/movimientos','VentasController@movimiento')->name('movimiento');

//Route del funcional inventario
Route::resource('medicamentos','MedicamentoController');
//Route::post('/medicamentos/{id}/update','MedicamentoController@update');

//Rutas para catalogo de existencias
Route::resource('catalogo','CatalogoExistenciaController');

//Rutas del kardex
Route::resource('kardex','RegistroController');

//sucursales
Route::resource('sucursal','SucursalController');
//::get('/sucursal', 'SucursalController@index');
/*Route::get('/create','SucursalController@vista') ;
Route::post('/create','SucursalController@create') ;
Route::get('/versucursales','SucursalController@read')->name('sucursales');*/

// vendedores
Route::resource('vendedor','VendedorController');
Route::get('/vendedor', 'VendedorController@index');
Route::get('/vendedorver', 'VendedorController@show');

Route::middleware(['auth'])->group(function(){
	//Roles
	Route::post('roles/store', 'RoleController@store')->name('roles.store')
	->middleware('permission:roles.create');

	Route::get('roles', 'RoleController@index')->name('roles.index')
	->middleware('permission:roles.index');

	Route::get('roles/create', 'RoleController@create')->name('roles.create')
	->middleware('permission:roles.create');

	Route::put('roles/{role}', 'RoleController@update')->name('roles.update')
	->middleware('permission:roles.edit');

	Route::get('roles/{role}', 'RoleController@show')->name('roles.show')
	->middleware('permission:roles.show');

	Route::delete('roles/{role}', 'RoleController@destroy')->name('roles.destroy')
	->middleware('permission:roles.destroy');

	Route::get('roles/{role}/edit', 'RoleController@edit')->name('roles.edit')
	->middleware('permission:roles.edit');

	//Usuarios
	Route::get('users', 'UserController@index')->name('users.index')
	->middleware('permission:users.index');

	Route::put('users/{user}', 'UserController@update')->name('users.update')
	->middleware('permission:users.edit');

	Route::get('users/{user}', 'UserController@show')->name('users.show')
	->middleware('permission:users.show');

	Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy')
	->middleware('permission:users.destroy');

	Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit')
	->middleware('permission:users.edit');

});

app/Sucursal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sucursal extends Model
{
    protected $table = 'sucurcales'; 
    protected $fillable = ['lugar', 'nombre','encargado'];
}

app/Http/Controllers/SucursalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Sucursal;

class SucursalController extends Controller
{
 
    public function index()
    {
        $sucursales = Sucursal::orderBy('id', 'DESC')->paginate(5);
        return view('sucursal.index', compact('sucursales'));
    }


    public function create()
    {
        return view('sucursal.create');
    }

 
    public function store(Request $request)
    {
       $this->validate($request,[ 'lugar'=>'required','nombre'=>'required', 'encargado'=>'required']);
        Sucursal::create($request->all());
        return redirect()->route('sucursal.index')->with('success','Registro creado satisfactoriamente');
      
    }


    public function show($id)
    {
        $sucursales=Sucursal::find($id);
        return  view('sucursal.show',compact('sucursales'));
    }


    public function edit($id)
    {
        $sucursal=Sucursal::find($id);
        return view('sucursal.edit',compact('sucursal'));
    }

 
    public function update(Request $request, $id)
    {
       $this->validate($request,[ 'lugar'=>'required','nombre'=>'required', 'encargado'=>'required']);
 
        Sucursal::find($id)->update($request->all());
        return redirect()->route('sucursal.index')->with('success','Registro actualizado satisfactoriamente');
 
    }


    public function destroy($id)
    {
        Sucursal::find($id)->delete();
        return redirect()->route('sucursal.index')->with('success','Registro eliminado satisfactoriamente');
   
    }
}

resources/views/sucursal/create.blade.php
@extends('layouts.layout')

@section('title')
Nueva sucursal
@endsection

@section('content')
<h2>Ingresar sucursal</h2>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{ route('sucursal.store') }}"  role="form">
							{{ csrf_field() }}
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<label>Nombre de la sucursal: </label>
										<input type="text" name="nombre" id="nombre" class="form-control input-sm" placeholder="Nombre de la sucursal">
									</div>
								</div>
								
							</div>
 							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										
										<label>Lugar/Direccion: </label>
										<input type="text" name="lugar" id="lugar" class="form-control input-sm" placeholder="lugar/Direccion">
								
							
									</div>
								</div>
						
							</div>
 						
							
							<div class="form-group">
								<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<label>Nombre del encargado: </label>
										<input type="text" name="encargado" id="encargado" class="form-control input-sm" placeholder="Nombre del Encargado">
									</div>
								</div>
						
							</div>
						
							<div class="row">
 
								 <div class="col-xs-1 col-sm-1 col-md-1">
                 					 <div class="form-group">
									<input type="submit"  value="Guardar" class="btn btn-success btn-block" width="20px">
								</div></div>	
								 <div class="col-xs-1 col-sm-1 col-md-1">
                 					 <div class="form-group">
									<a href="{{ route('sucursal.index') }}" class="btn btn-info btn-block" width="20px">Atrás</a>
								</div>	
								</div>
 
							</div>
						</form>
					</div>
@endsection

resources/views/sucursal/edit.blade.php
@extends('layouts.layout')

@section('title')
Sucursal
@endsection

@section('title-1')
GESTION DE SUCURSALES
@endsection

@section('content')
	
<div class="table-container">
            <form method="POST" action="{{ route('sucursal.update',$sucursal->id) }}"  role="form">
              {{ csrf_field() }}
              <input name="_method" type="hidden" value="PATCH">
              <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                  <div class="form-group">
                    <label>Nombre de la sucursal: </label>
                    <input type="text" name="nombre" id="nombre" class="form-control input-sm" value="{{$sucursal->nombre}}">
                  </div>
                </div>
                </div>
                <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                  <div class="form-group">
                    <label>Lugar/Direccion: </label>
                    <input type="text" name="lugar" id="lugar" class="form-control input-sm" value="{{$sucursal->lugar}}">
                  </div>
                </div>
              </div>

              <div class="row">

                <div class="col-xs-6 col-sm-6 col-md-6">
                  <div class="form-group">
                    <label>Nombre del encargado: </label>
                    <input type="text" name="encargado" id="encargado" class="form-control input-sm" value="{{$sucursal->encargado}}">
                  </div>
                </div>
              </div>

              <div class="row">

                <div class="col-xs-1 col-sm-1 col-md-1">
                  <div class="form-group">
                  <input type="submit"  value="Actualizar" class="btn btn-success btn-block">
                  </div>  
                  </div> 
                  <div class="col-xs-1 col-sm-1 col-md-1">
                  <div class="form-group"> 
                  <a href="{{ route('sucursal.index') }}" class="btn btn-info btn-block" >Atrás</a>
                </div>  

              </div>
            </form>
          </div>
     
      
@endsection

resources/views/sucursal/index.blade.php
@extends('layouts.layout')

@section('title')
Sucursal
@endsection

@section('title-1')
GESTION DE SUCURSALES
@endsection

@section('content')
<div class="pull-left"><h3>Gestion de Sucursales</h3></div>
          <div class="pull-right">
            <div class="btn-group">
              <a href="{{ route('sucursal.create') }}" class="btn btn-info" >Nueva Sucursal</a>
            </div>
          </div>	
<div class="table-container">
            <table id="mytable" class="table table-bordred table-striped">
             <thead>
               	<th width="20px">ID</th>
				<th>Nombre de la farmacia</th>
				<th>Lugar/ubicacion</th>
				<th>Encargado</th>
				
				<th colspna="3">Acciones</th>

             </thead>
             <tbody>
             	@foreach($sucursales as $sucursales)
				<tr>
					<td>{{ $sucursales->id }}</td>
					<td>{{ $sucursales->nombre}}</td>
					<td>{{ $sucursales->lugar}}</td>
					<td>{{ $sucursales->encargado}} </td>
					<td><a class="btn btn-primary btn-xs" href="{{action('SucursalController@edit', $sucursales->id)}}" ><span class="glyphicon glyphicon-pencil"></span></a></td>
                <td>
                  <form action="{{action('SucursalController@destroy', $sucursales->id)}}" method="post">
                   {{csrf_field()}}
                   <input name="_method" type="hidden" value="DELETE">
 
                   <button class="btn btn-danger btn-xs" type="submit"><span class="glyphicon glyphicon-trash"></span></button>
                 </td>
               </tr>
                @endforeach
            </tbody>
 
          </table>
        </div>
     
      
@endsection