routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categorias', 'CategoriaController');
Route::resource('presentaciones', 'PresentacionController');


Route::resource('compras','CompraController');


Route::resource('presentaciones', 'PresentacionController');



//Route::get('/home/inventariomedicamento', 'ControllerInventario@index')->name('index');
Route::resource('inventario', 'ControllerInventario');
//Route::resource('inventario', 'inventario');


//Rutas de ventas
Route::resource('ventas','VentasController');
Route::get('/buscador','VentasController@buscador')->name('buscador');
Route::post('/buscador','VentasController@buscador')->name('buscador');
Route::get('/movimientos','VentasController@movimiento')->name('movimiento');

//Route del funcional inventario
Route::resource('medicamentos','MedicamentoController');
//Route::post('/medicamentos/{id}/update','MedicamentoController@update');

//Rutas para catalogo de existencias
Route::resource('catalogo','CatalogoExistenciaController');

//Rutas del kardex
Route::resource('kardex','RegistroController');

//sucursales
Route::resource('sucursal','SucursalController');
//::get('/sucursal', 'SucursalController@index');
/*Route::get('/create','SucursalController@vista') ;
Route::post('/create','SucursalController@create') ;
Route::get('/versucursales','SucursalController@read')->name('sucursales');*/

// vendedores
Route::resource('vendedor','VendedorController');
Route::get('/vendedor', 'VendedorController@index');
Route::get('/vendedorver', 'VendedorController@show');

Route::middleware(['auth'])->group(function(){
	//Roles
	Route::post('roles/store', 'RoleController@store')->name('roles.store')
	->middleware('permission:roles.create');

	Route::get('roles', 'RoleController@index')->name('roles.index')
	->middleware('permission:roles.index');

	Route::get('roles/create', 'RoleController@create')->name('roles.create')
	->middleware('permission:roles.create');

	Route::put('roles/{role}', 'RoleController@update')->name('roles.update')
	->middleware('permission:roles.edit');

	Route::get('roles/{role}', 'RoleController@show')->name('roles.show')
	->middleware('permission:roles.show');

	Route::delete('roles/{role}', 'RoleController@destroy')->name('roles.destroy')
	->middleware('permission:roles.destroy');

	Route::get('roles/{role}/edit', 'RoleController@edit')->name('roles.edit')
	->middleware('permission:roles.edit');

	//Usuarios
	Route::get('users', 'UserController@index')->name('users.index')
	->middleware('permission:users.index');

	Route::put('users/{user}', 'UserController@update')->name('users.update')
	->middleware('permission:users.edit');

	Route::get('users/{user}', 'UserController@show')->name('users.show')
	->middleware('permission:users.show');

	Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy')
	->middleware('permission:users.destroy');

	Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit')
	->middleware('permission:users.edit');

});

app/Categoria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
    protected $fillable = [
        'nombre', 'descripcion',
    ];

    public function medicamentos()
    {
        return $this->hasMany('App\Mediacmento', 'idCategoria', 'id');
    }
}

app/Http/Controllers/CategoriaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Categoria;

class CategoriaController extends Controller
{
    public function index(){
    	$categorias = Categoria::orderBy('id', 'DESC')->paginate(5);
    	return view('categorias.index', compact('categorias'));
    }
    public function destroy($id){
    	$categoria = Categoria::find($id);
    	$categoria->delete();
    return back()->with('info', 'La categoria: '.$categoria->id.', fue eliminada');
    }
    public function create(){
        return view('categorias.create');
    }

    public function store(){
        $data = request()->all();
        Categoria::create([
            'nombre'      => $data['nombre'],
            'descripcion' => $data['descripcion'],
            ]);
        return redirect()->route('categorias.index');
    }

    public function edit($id){
        $categoria = Categoria::find($id);
        return view('categorias.edit', compact('categoria'));
    }

    public function update($id){
        $data = request()->all();

        $categoria = Categoria::find($id);
        $categoria->update([
            'nombre'      => $data['nombre'],
            'descripcion' => $data['descripcion'],
            ]);
        return redirect()->route('categorias.index');
    }
}

resources/views/categorias/create.blade.php
@extends('layouts.layout')

@section('title')
Categoria - Nueva
@endsection

@section('content')
<h2>Nueva categoria</h2>
<form class="form-inline" style="width:100%" action="{{ route('categorias.store' )}}" method="POST">
	{{ csrf_field() }}

	<div class="form-group">
		<label for="nombre">Nombre:</label><br>
		<input type="text" class="form-control" style="width:100%" name="nombre" >
	</div><br><br>
	<div class="form-group">
		<label for="nombre">Descripcion:</label><br>
		<textarea class="form-control" style="width:110%" name="descripcion" rows="6"></textarea>
	</div><br><br>

	<button type="submit" class="btn btn-success">Guardar</button>
	<a class="btn btn-default" style="text-decoration:none;color:black" href="{{ route('categorias.index')}}">Cancelar</a>
</form>
@endsection

resources/views/categorias/edit.blade.php
@extends('layouts.layout')

@section('title')
Categorias - Edicion
@endsection

@section('content')
<h2>Edicion de: {{$categoria->nombre}}</h2>
<form class="form-inline" style="width:100%" action="{{ route('categorias.update', $categoria->id)}}" method="POST">
	{{ csrf_field() }}

	<input name="_method" value="PUT" type="hidden"> 

	<div class="form-group">
		<label for="nombre">Nombre:</label><br>
		<input type="text" class="form-control" style="width:100%" name="nombre" value="{{ $categoria->nombre }}">
	</div><br><br>
	<div class="form-group">
		<label for="nombre">Descripcion:</label><br>
		<textarea class="form-control" style="width:110%" name="descripcion" value="{{ $categoria->descripcion }}" rows="6">{{ $categoria->descripcion }}</textarea>
	</div><br><br>

	<button type="submit" class="btn btn-success">Guardar</button>
	<a class="btn btn-default" style="text-decoration:none;color:black" href="{{ route('categorias.index')}}">Cancelar</a>
</form>
@endsection

resources/views/categorias/index.blade.php
@extends('layouts.layout')

@section('title')
Categorias
@endsection

@section('title-1')
Lista de categorias
@endsection

@section('content')
	
	<div class="clo-sm-8">
		<h2>
			<div style="display:inline;opacity:0">.</div>
			<div style="display:inline"><a href="{{ route('categorias.create')}}" class="btn btn-primary pull-right">Nuevo</a></div>
			
		</h2>		

		@include('categorias.fragment.info')
	<table class="table table-hover table-striped">
		<thead>
			<tr>
				<th width="20px">ID</th>
				<th>Nombre</th>
				<th>Descripcion</th>
				<th colspna="3">Acciones</th>
			</tr>
			<tbody>
				@foreach($categorias as $categoria)
				<tr>
					<td>{{ $categoria->id }}</td>
					<td style="width:27%">{{ $categoria->nombre }}</td>
					<td style="width:100%">{{ $categoria->descripcion }}</td>
					{{-- <td>
						<a href="{{ route('categorias.show', $categoria->id)}}" class="btn btn-info pull-right">Ver</a>
					</td> --}}
					<td>
						<a href="{{ route('categorias.edit', $categoria->id)}}" class="btn btn-warning pull-right">Editar</a>
					</td>
					<td>
						<form action="{{ route('categorias.destroy', $categoria->id)}}" method="POST">
						{{ csrf_field() }}
						<input type="hidden" name="_method"value="DELETE">
						<button class="btn btn-danger">Eliminar</button>
						</form>
					</td>
				</tr>
				@endforeach
			</tbody>
		</thead>
	</table>
	{!! $categorias->render() !!}
	</div>
@endsection

resources/views/categorias/show.blade.php
@extends('layouts.layout')

@section('content')
	<div class="clo-sm-8">
		<h2>
			{{ $categoria->nombre}}}
		</h2>
	{!! $categoria->descripcion !!}
	</div>
@endsection