routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categorias', 'CategoriaController');
Route::resource('presentaciones', 'PresentacionController');


Route::resource('compras','CompraController');


Route::resource('presentaciones', 'PresentacionController');



//Route::get('/home/inventariomedicamento', 'ControllerInventario@index')->name('index');
Route::resource('inventario', 'ControllerInventario');
//Route::resource('inventario', 'inventario');


//Rutas de ventas
Route::resource('ventas','VentasController');
Route::get('/buscador','VentasController@buscador')->name('buscador');
Route::post('/buscador','VentasController@buscador')->name('buscador');
Route::get('/movimientos','VentasController@movimiento')->name('movimiento');

//Route del funcional inventario
Route::resource('medicamentos','MedicamentoController');
//Route::post('/medicamentos/{id}/update','MedicamentoController@update');

//Rutas para catalogo de existencias
Route::resource('catalogo','CatalogoExistenciaController');

//Rutas del kardex
Route::resource('kardex','RegistroController');

//sucursales
Route::resource('sucursal','SucursalController');
//::get('/sucursal', 'SucursalController@index');
/*Route::get('/create','SucursalController@vista') ;
Route::post('/create','SucursalController@create') ;
Route::get('/versucursales','SucursalController@read')->name('sucursales');*/

// vendedores
Route::resource('vendedor','VendedorController');
Route::get('/vendedor', 'VendedorController@index');
Route::get('/vendedorver', 'VendedorController@show');

Route::middleware(['auth'])->group(function(){
	//Roles
	Route::post('roles/store', 'RoleController@store')->name('roles.store')
	->middleware('permission:roles.create');

	Route::get('roles', 'RoleController@index')->name('roles.index')
	->middleware('permission:roles.index');

	Route::get('roles/create', 'RoleController@create')->name('roles.create')
	->middleware('permission:roles.create');

	Route::put('roles/{role}', 'RoleController@update')->name('roles.update')
	->middleware('permission:roles.edit');

	Route::get('roles/{role}', 'RoleController@show')->name('roles.show')
	->middleware('permission:roles.show');

	Route::delete('roles/{role}', 'RoleController@destroy')->name('roles.destroy')
	->middleware('permission:roles.destroy');

	Route::get('roles/{role}/edit', 'RoleController@edit')->name('roles.edit')
	->middleware('permission:roles.edit');

	//Usuarios
	Route::get('users', 'UserController@index')->name('users.index')
	->middleware('permission:users.index');

	Route::put('users/{user}', 'UserController@update')->name('users.update')
	->middleware('permission:users.edit');

	Route::get('users/{user}', 'UserController@show')->name('users.show')
	->middleware('permission:users.show');

	Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy')
	->middleware('permission:users.destroy');

	Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit')
	->middleware('permission:users.edit');

});

app/inventario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class inventario extends Model
{
  protected $table = 'inventario';
    protected $fillable = [
       'idmedicamento', 'idsucursal','Nombre', 'cantidadMinima','fecha_registro'
    ];

    public function detalleInventario()
         {
         	return $this->hasMany('App\inventario', 'idmedicamento', 'idmedicamento');
         }
   
}

app/Http/Controllers/InventarioController.php
 <?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Inventario;
class InventarioController extends Controller
{
    //
    public function create(Request $request){
    	$inventario = new Inventario();

    	$inventario -> cantidad = $request -> cantidad;
    	$inventario -> nombre = $request -> nombre;
    	$inventario -> idsucursal = $request -> idsucursal;
    }
}

resources/views/inventario/create.blade.php
@extends('layouts.layout')

@section('title')
Inventario - Nuevo
@endsection

@section('content')
<h2>Ingreso de medicamento</h2>
<form class="form-inline" style="width:100%" action="{{ route('inventario.store' )}}" method="POST">
	{{ csrf_field() }}
	<div class="form-group">
		<label for="fecha">Fecha :</label><br>
		<input type="date" class="form-control"  name="fecha">
	</div><br>
	<div class="form-group">
		<label for="proveedor">Nombre :</label><br>
		<input type="text" class="form-control"  name="proveedor">
	</div><br>
	<div class="form-group">
		<label for="proveedor">Cantidad de producto :</label><br>
		<input type="text" class="form-control"  name="proveedor">
	</div><br>

	<button type="submit" class="btn btn-success">Guardar</button>
	<button type="button" class="btn btn-secondary"><a style="text-decoration:none;color:black" href="{{ route('inventario.index')}}">Cancelar</a></button>
</form>

@endsection

resources/views/inventario/edit.blade.php
<!-- @extends('layouts.layout')

@section('title') --> 
Inventario - Edicion
<!-- @endsection

@section('content') -->
<h2>Edicion de: <!-- {{$inventario->idmedicamento}}  -->
</h2>
<form class="form-inline" style="width:100%" action="{{ route('inventario.update', $inventario->id)}}" method="POST">
	<!-- {{ csrf_field() }} -->

	<input name="_method" value="PUT" type="hidden"> 

	<div class="form-group">
		<label for="idmedicamento">ID Medicamento:</label><br>
		<input type="text" class="form-control" style="width:100%" name="idmedicamento" value="{{ $inventario->idmedicamento }}">
	</div><br><br>
	<div class="form-group">
		<label for="Nombre">Nombre:</label><br>
		<input type="number" class="form-control" style="width:100%" name="Nombre" value="{{ $inventario->Nombre }}">
	</div><br><br>
	<div class="form-group">
		<label for="cantidad">Cantidad:</label><br>
		<input type="number" class="form-control" style="width:100%" name="cantidad" value="{{ $inventario->cantidad }}">
	</div><br><br>

	<div class="form-group">
		<label for="fecha">Fecha modificacion:</label><br>
		<input type="date" class="form-control" style="width:100%" name="fecha" value="{{ $inventario->fecha }}">
	</div><br><br>

	<button type="submit" class="btn btn-success">Guardar</button>

	<button type="button" class="btn btn-secondary"><a style="text-decoration:none;color:black" href="{{ route('inventarios.index')}}">Cancelar</a></button>
</form>
<!-- @endsection

resources/views/inventario/index.blade.php
@extends('layouts.layout')

@section('title')
Inventario
@endsection

@section('title-1')
GESTION DE INVENTARIO/MEDICAMENTO
@endsection

@section('content')
	
	<div class="clo-sm-8">
		<h2>
			Lista de inventarios
			<a href="{{ route('inventario.create')}}" class="btn btn-primary pull-right">Nuevo</a>
		</h2>		

		@include('inventario.fragment.info')
	<table class="table table-hover table-striped">
		<thead>
			<tr>
				<th width="20px">ID Medicamento</th>
				<th>ID sucursal</th>
				<th>Cantidad Minima</th>
				<th>Nombre</th>
				<th>Fecha Modificacion</th>
				
				<th colspna="3">Acciones a realizar</th>
			</tr>
			<tbody>
				@foreach($inventario as $inventario)
				<tr>
					<td>{{ $inventario->idmedicamento }}</td>
					<td>{{ $inventario->idsucursal }}</td>
					<td>{{ $inventario->cantidadMin }}</td>
					<td>{{ $inventario->Nombre}} </td>
					<td>{{ $inventario->fecha_registro}} </td>
					<td>
						<a href="{{ route('inventario.show', $inventario->id)}}" class="btn btn-warning pull-right">Ver Detalles</a>
					</td>
				</tr>
				@endforeach
			</tbody>
		</thead>
	</table>
	{!! $inventario->render() !!}
	</div>
@endsection

resources/views/inventario/show.blade.php
@extends('layouts.layout')
@section('title')
INVENTARIO
@endsection

@section('content') -->
<h2>Detalle Inventario</h2>
    
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>ID Medicamento</th>
        <th>ID sucursal</th>
        <th>Cantidad </th>
        <th>Nombre</th>
        <th>Fecha ingreso</th>
      </tr>
      <tbody>
        @foreach($arreglo as $de)
        <tr>
          <td>{{ $de['idmedicamento'] }}</td>
        </tr>
        @endforeach
      </tbody>
    </thead>
  </table>
    <button type="button" class="btn btn btn-success"><a style="text-decoration:none;color:black" href="{{ route('inventario.index')}}">Regresar</a></button>



 @endsection